/**
 * Report archive, period-close snapshots, reproducibility and the monthly management pack
 * (spec 250–254, 260–261). Reports are generated by the full-cost export engine; this module
 * archives them with their parameters and hashes and proves that closed months reproduce.
 */
import { createHash } from "node:crypto";
import type { CostPeriod } from "@prisma/client";
import { DomainError } from "@/domain/errors";
import type { Db, Tx } from "../db";
import { type Actor, authorize, can } from "../auth/actor";
import { audit } from "./audit";
import { buildFullCostExport, PERIOD_BOUND_SECTIONS, type FullCostExport } from "./export";
import { closeChecklist, reconciliationStatus } from "./period";
import { theoreticalVsActual, serializeVariance } from "./variance";
import { renderManagementPack } from "../reports/pack-pdf";
import type { Locale } from "@/i18n/core";

const dayAfter = (d: Date) => new Date(d.getTime() + 86_400_000);

/** Snapshot taken inside the close transaction (spec 253): calculated metrics + hashes, archived as PERIOD_CLOSE. */
export async function periodCloseSnapshot(tx: Tx, actor: Actor, hotelId: string, period: CostPeriod) {
  const from = period.startDate;
  const to = dayAfter(period.endDate);
  if (!can(actor, "report:export")) {
    return { variance: serializeVariance(await theoreticalVsActual(tx, actor, hotelId, { from, to })) };
  }
  const e = await buildFullCostExport(tx, actor, hotelId, { from, to }, { noArchive: true });
  const checks = await closeChecklist(tx, hotelId, period);
  const status = reconciliationStatus(checks, e.score.errors);
  const data = { exportId: e.exportId, exportVersion: e.exportVersion, summary: e.summary, checks: e.checks, closeChecks: checks, reconciliation: status, score: e.score, counts: e.counts, sectionHashes: e.meta.sectionHashes };
  const r = await tx.report.create({ data: { hotelId, reportType: "PERIOD_CLOSE", periodId: period.id, periodFrom: from, periodTo: to, params: {}, generatedById: actor.userId, contentHash: e.meta.contentHash, periodHash: e.meta.periodHash, data: JSON.parse(JSON.stringify(data)) } });
  return { reportId: r.id, periodHash: e.meta.periodHash, contentHash: e.meta.contentHash, reconciliation: status, summary: e.summary };
}

export async function listReports(db: Db, actor: Actor, hotelId: string, take = 100) {
  authorize(actor, "report:view", { hotelId });
  const rows = await db.report.findMany({ where: { hotelId }, orderBy: { generatedAt: "desc" }, take, select: { id: true, reportType: true, periodId: true, periodFrom: true, periodTo: true, params: true, generatedById: true, generatedAt: true, dataVersion: true, contentHash: true, periodHash: true } });
  const [users, periods] = await Promise.all([
    db.user.findMany({ where: { id: { in: [...new Set(rows.map((r) => r.generatedById))] } }, select: { id: true, name: true } }),
    db.costPeriod.findMany({ where: { hotelId, id: { in: rows.map((r) => r.periodId).filter((x): x is string => !!x) } } }),
  ]);
  return rows.map((r) => ({ ...r, generatedBy: users.find((u) => u.id === r.generatedById)?.name ?? "—", period: periods.find((p) => p.id === r.periodId) ?? null }));
}

/**
 * Reproducibility check (spec 252): rebuild the report with its stored parameters and compare the
 * period-bound section hashes. A closed, never-reopened month must reproduce exactly.
 */
export async function verifyReproducibility(db: Db, actor: Actor, hotelId: string, reportId: string) {
  authorize(actor, "report:export", { hotelId });
  const r = await db.report.findFirst({ where: { id: reportId, hotelId } });
  if (!r) throw new DomainError("NOT_FOUND", "Report not found");
  if (!r.periodFrom || !r.periodTo || !r.periodHash) throw new DomainError("VALIDATION", "This report has no reproducibility fingerprint (generated before archiving was introduced)");
  const params = (r.params ?? {}) as { departmentId?: string | null; warehouseId?: string | null; categoryGroup?: string | null; scope?: "ALL" | string[] };
  // the rebuild replays the department scope the report was made with (reports from before the scope was stored were
  // hotel-wide). Whoever verifies must see at least that scope; a narrower rebuild would always report CHANGED
  const scope = params.scope ?? "ALL";
  const covers = actor.departmentIds === "ALL" || (scope !== "ALL" && scope.every((id) => actor.departmentIds.includes(id)));
  if (!covers) throw new DomainError("FORBIDDEN", scope === "ALL" ? "Verifying a report rebuilds the whole hotel: needs an all-department role" : "This report covers departments outside your access");
  const replay: Actor = scope === "ALL" ? actor : { ...actor, departmentIds: scope };
  const e = await buildFullCostExport(db, replay, hotelId, { from: r.periodFrom, to: r.periodTo, departmentId: params.departmentId ?? undefined, warehouseId: params.warehouseId ?? undefined, categoryGroup: params.categoryGroup ?? undefined }, { noArchive: true });
  const data = r.data as { sectionHashes?: Record<string, string>; meta?: { sectionHashes?: Record<string, string> } };
  const before = data.sectionHashes ?? data.meta?.sectionHashes ?? {};
  const differences = PERIOD_BOUND_SECTIONS.filter((k) => (before[k] ?? null) !== (e.meta.sectionHashes[k] ?? null));
  const period = r.periodId ? await db.costPeriod.findUnique({ where: { id: r.periodId } }) : null;
  const reopened = period ? await db.auditLog.findFirst({ where: { hotelId, entityType: "CostPeriod", entityId: period.id, action: "PERIOD_REOPEN", createdAt: { gt: r.generatedAt } }, orderBy: { createdAt: "desc" } }) : null;
  const result = { reportId: r.id, reportType: r.reportType, reproducible: e.meta.periodHash === r.periodHash, originalHash: r.periodHash, currentHash: e.meta.periodHash, differences, periodStatus: period?.status ?? null, reopenedAt: reopened?.createdAt ?? null, reopenReason: reopened?.reason ?? null, checkedAt: new Date().toISOString() };
  await audit(db, actor, { hotelId, action: "REPORT_VERIFY", entityType: "Report", entityId: r.id, after: { reproducible: result.reproducible, differences } });
  return result;
}

/** Monthly management cost pack (spec 254) as PDF; archived with its hashes. */
export async function managementPack(db: Db, actor: Actor, hotelId: string, q: { from: Date; to: Date }, locale: Locale = "en") {
  authorize(actor, "report:export", { hotelId });
  if (actor.departmentIds !== "ALL") throw new DomainError("FORBIDDEN", "The management pack is hotel-wide: needs an all-department role");
  const e: FullCostExport = await buildFullCostExport(db, actor, hotelId, q, { noArchive: true });
  const period = await db.costPeriod.findFirst({ where: { hotelId, startDate: { lte: q.from }, endDate: { gte: q.from } } });
  const closeChecks = period ? await closeChecklist(db, hotelId, period) : [];
  const reconciliation = reconciliationStatus(closeChecks, e.score.errors);
  const pdf = await renderManagementPack(e, { reconciliation, closeChecks, periodStatus: period?.status ?? "NO PERIOD" }, locale);
  const pdfHash = createHash("sha256").update(pdf).digest("hex");
  const r = await db.report.create({ data: { hotelId, reportType: "MANAGEMENT_PACK", periodId: period?.id ?? null, periodFrom: q.from, periodTo: q.to, params: {}, generatedById: actor.userId, contentHash: e.meta.contentHash, periodHash: e.meta.periodHash, data: JSON.parse(JSON.stringify({ exportId: e.exportId, pdfHash, pages: null, reconciliation, summary: e.summary, sectionHashes: e.meta.sectionHashes, score: e.score })) } });
  await audit(db, actor, { hotelId, action: "REPORT_MANAGEMENT_PACK", entityType: "Report", entityId: r.id, after: { period: e.meta.period, reconciliation, pdfHash } });
  return { pdf, report: r, fileName: `HotelCost_Management_Pack_${e.meta.hotel.code}_${e.meta.period.from.slice(0, 7)}.pdf`, reconciliation };
}
