/** Embeds src/server/excel/vba/*.bas|*.cls into a TS module so the server bundle needs no file access. */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const dir = path.join(process.cwd(), "src/server/excel/vba");
const files = readdirSync(dir).filter((f) => /\.(bas|cls)$/.test(f)).sort();
const entries = files.map((f) => `  ${JSON.stringify(f.replace(/\.(bas|cls)$/, ""))}: ${JSON.stringify(readFileSync(path.join(dir, f), "utf8"))},`);
writeFileSync(
  path.join(process.cwd(), "src/server/excel/vba-sources.generated.ts"),
  `// AUTO-GENERATED by scripts/gen-vba.ts from src/server/excel/vba — do not edit by hand.\nexport const VBA_SOURCES: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
);
console.log(`Embedded ${files.length} VBA modules`);
